// Generated by CoffeeScript 1.7.1
(function() {
  var req;

  req = require('./api/req');

  module.exports = req;

  module.exports.require = req;

  module.exports.install = require('./api/install');

  module.exports.list = require('./api/list');

  module.exports.current = require('./api/current');

  module.exports.remove = require('./api/remove');

}).call(this);
