// Generated by CoffeeScript 1.7.1
(function() {
  var child_process,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  child_process = require('child_process');

  module.exports = function(pkg, callback) {
    var cmd;
    if (pkg.indexOf('@') > -1) {
      return callback(new Error('Version is not required'));
    }
    cmd = 'npm show ' + pkg + ' version 2> /dev/null';
    return child_process.exec(cmd, function(err, stdout, stderr) {
      var current;
      if (err) {
        return callback(err);
      }
      current = stdout.replace(/^\s+|\s+$/g, '');
      return require('./list')(pkg, function(err, versions) {
        return callback(null, current, versions && __indexOf.call(versions, current) >= 0, versions);
      });
    });
  };

  module.exports.cache = {};

}).call(this);
