// Generated by CoffeeScript 1.7.1
(function() {
  var dir, fs, list;

  fs = require('fs');

  dir = require('./dir');

  list = require('./list');

  module.exports = function(callback) {
    var count, dict, errors, total;
    errors = [];
    count = 0;
    total = null;
    dict = {};
    return fs.readdir(dir, function(err, pkgs) {
      var pkg, _i, _j, _len, _len1, _results;
      if (err || !pkgs.length) {
        return callback(err, {});
      }
      total = pkgs.length;
      for (_i = 0, _len = pkgs.length; _i < _len; _i++) {
        pkg = pkgs[_i];
        dict[pkg] = null;
      }
      _results = [];
      for (_j = 0, _len1 = pkgs.length; _j < _len1; _j++) {
        pkg = pkgs[_j];
        _results.push((function(pkg) {
          return list(pkg, function(err, versions) {
            if (err) {
              errors.push(err);
              delete dict[pkg];
            } else if (!(versions && versions.length)) {
              delete dict[pkg];
            } else {
              dict[pkg] = versions;
            }
            count += 1;
            if (count === total) {
              if (errors.length) {
                return callback(errors);
              }
              return callback(null, dict);
            }
          });
        })(pkg));
      }
      return _results;
    });
  };

}).call(this);
