// Generated by CoffeeScript 1.7.1
(function() {
  var current, dir, fs;

  fs = require('fs');

  current = require('./current');

  dir = require('./dir');

  module.exports = function(pkg, callback) {
    if (typeof pkg === 'function') {
      return require('./list-all')(pkg);
    }
    if (!pkg) {
      return require('./list-all')(callback);
    }
    if (pkg.indexOf('@') > -1) {
      return callback(new Error('Version is not required'));
    }
    return fs.exists(dir + '/' + pkg, function(exists) {
      if (!exists) {
        return callback(null, false);
      }
      return fs.readdir(dir + '/' + pkg, function(err, versions) {
        delete current.cache[pkg];
        if (!versions.length) {
          return callback(null, false);
        }
        if (versions && versions.length) {
          current.cache[pkg] = versions[versions.length - 1];
        }
        return callback(null, versions);
      });
    });
  };

}).call(this);
