// Generated by CoffeeScript 1.7.1
(function() {
  var child_process, dir, fs;

  child_process = require('child_process');

  fs = require('fs');

  dir = require('./dir');

  module.exports = function(spec, callback) {
    var pkg, req, rm_dir, version, _ref;
    _ref = spec.split('@'), pkg = _ref[0], version = _ref[1];
    console.log('[dynmod] removing ' + spec);
    if (version) {
      if ((req = require('./req')).cache[pkg] != null) {
        delete req.cache[pkg][version];
      }
      rm_dir = dir + '/' + pkg + '/' + version;
    } else {
      delete require('./req').cache[pkg];
      rm_dir = dir + '/' + pkg;
    }
    return child_process.exec('rm -rf ' + rm_dir, function(err) {
      if (err) {
        return callback(err);
      }
      if (!version) {
        return callback();
      }
      return fs.readdir(dir + '/' + pkg, function(err, files) {
        if (err || (files && files.length)) {
          return callback();
        }
        return child_process.exec('rm -rf ' + dir + '/' + pkg, function(err) {
          return callback();
        });
      });
    });
  };

}).call(this);
